name: meteoappv3
description: A weather application using OpenWeatherMap API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  geolocator: ^14.0.0
  background_fetch: ^1.3.8
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
